
import java.awt.Color;
import java.awt.Font;
import static java.lang.Math.pow;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Killer
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    /**
     * Creates new form TelaPrincipal
     */
    public int nTA,nTV,nMA,nMV,nBB,nBBA,nBBV,nTRA,nTRV;
    public String sitA,sitB;
    
    public TelaPrincipal() {
        initComponents();
        lblSitA.setVisible(false);
        lblSitB.setVisible(false);
        labelClima.setVisible(false);
        lblClima.setVisible(false);
        labelTerreno.setVisible(false);
        lblTerreno.setVisible(false);
        labelBV.setVisible(false);
        labelBV.setVisible(false);
        lblNBV.setVisible(false);
        lblResultado.setVisible(false);
        btnBatalha.setVisible(false);
        labelBA.setVisible(false);
        lblNBA.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnGerar = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblNTA = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblMA = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblSitA = new javax.swing.JLabel();
        labelBA = new javax.swing.JLabel();
        lblNBA = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblNTA1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblNTV = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblMV = new javax.swing.JLabel();
        lblSitB = new javax.swing.JLabel();
        labelBV = new javax.swing.JLabel();
        lblNBV = new javax.swing.JLabel();
        lblClima = new javax.swing.JLabel();
        lblTerreno = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnBatalha = new javax.swing.JButton();
        labelClima = new javax.swing.JLabel();
        labelTerreno = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGerar.setFont(new java.awt.Font("GungsuhChe", 1, 18)); // NOI18N
        btnGerar.setForeground(new java.awt.Color(0, 102, 51));
        btnGerar.setText("GERAR!");
        btnGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 100, -1));

        lblResultado.setFont(new java.awt.Font("GungsuhChe", 1, 24)); // NOI18N
        lblResultado.setForeground(new java.awt.Color(0, 51, 51));
        lblResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResultado.setText("RESULTADO");
        jPanel1.add(lblResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 680, -1));

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 204)));
        jPanel2.setMinimumSize(new java.awt.Dimension(250, 250));
        jPanel2.setPreferredSize(new java.awt.Dimension(250, 250));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bluesoldier_1.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 40, -1, -1));

        jLabel6.setFont(new java.awt.Font("GungsuhChe", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 255));
        jLabel6.setText("Num. de Tropas :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 36, -1, -1));

        lblNTA.setFont(new java.awt.Font("GungsuhChe", 1, 14)); // NOI18N
        lblNTA.setForeground(new java.awt.Color(0, 51, 255));
        lblNTA.setText("0");
        jPanel2.add(lblNTA, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 36, -1, -1));

        jLabel8.setFont(new java.awt.Font("GungsuhChe", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 255));
        jLabel8.setText("Moral :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 59, -1, -1));

        lblMA.setFont(new java.awt.Font("GungsuhChe", 1, 14)); // NOI18N
        lblMA.setForeground(new java.awt.Color(0, 51, 255));
        lblMA.setText("0");
        jPanel2.add(lblMA, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 59, -1, -1));

        jLabel1.setFont(new java.awt.Font("GungsuhChe", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("Exército Azul");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lblSitA.setFont(new java.awt.Font("GungsuhChe", 1, 14)); // NOI18N
        lblSitA.setForeground(new java.awt.Color(0, 51, 255));
        lblSitA.setText("SITUAÇÃO");
        jPanel2.add(lblSitA, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        labelBA.setFont(new java.awt.Font("GungsuhChe", 1, 14)); // NOI18N
        labelBA.setForeground(new java.awt.Color(0, 51, 255));
        labelBA.setText("Num. de Baixas :");
        jPanel2.add(labelBA, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        lblNBA.setFont(new java.awt.Font("GungsuhChe", 1, 14)); // NOI18N
        lblNBA.setForeground(new java.awt.Color(0, 51, 255));
        lblNBA.setText("0");
        jPanel2.add(lblNBA, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 61, 280, 250));

        jPanel3.setBackground(new java.awt.Color(255, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("GungsuhChe", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 0));
        jLabel5.setText("Exército Vermelho");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/redsoldier_1.png"))); // NOI18N
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 40, -1, -1));

        jLabel9.setFont(new java.awt.Font("GungsuhChe", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 255));
        jLabel9.setText("Num. de Tropas :");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 191, -1, -1));

        lblNTA1.setFont(new java.awt.Font("GungsuhChe", 1, 14)); // NOI18N
        lblNTA1.setForeground(new java.awt.Color(0, 51, 255));
        lblNTA1.setText("0");
        jPanel3.add(lblNTA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 39, -1, -1));

        jLabel11.setFont(new java.awt.Font("GungsuhChe", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 255));
        jLabel11.setText("Moral :");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 39, -1, -1));

        jLabel12.setFont(new java.awt.Font("GungsuhChe", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 255));
        jLabel12.setText("SITUAÇÃO");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 113, -1, -1));

        jLabel15.setFont(new java.awt.Font("GungsuhChe", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 0, 0));
        jLabel15.setText("Num. de Tropas :");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        lblNTV.setFont(new java.awt.Font("GungsuhChe", 1, 14)); // NOI18N
        lblNTV.setForeground(new java.awt.Color(153, 0, 0));
        lblNTV.setText("0");
        jPanel3.add(lblNTV, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        jLabel16.setFont(new java.awt.Font("GungsuhChe", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 0, 0));
        jLabel16.setText("Moral :");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        lblMV.setFont(new java.awt.Font("GungsuhChe", 1, 14)); // NOI18N
        lblMV.setForeground(new java.awt.Color(153, 0, 0));
        lblMV.setText("0");
        jPanel3.add(lblMV, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, -1));

        lblSitB.setFont(new java.awt.Font("GungsuhChe", 1, 14)); // NOI18N
        lblSitB.setForeground(new java.awt.Color(153, 0, 0));
        lblSitB.setText("SITUAÇÃO");
        jPanel3.add(lblSitB, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        labelBV.setFont(new java.awt.Font("GungsuhChe", 1, 14)); // NOI18N
        labelBV.setForeground(new java.awt.Color(153, 0, 0));
        labelBV.setText("Num. de Baixas :");
        jPanel3.add(labelBV, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        lblNBV.setFont(new java.awt.Font("GungsuhChe", 1, 14)); // NOI18N
        lblNBV.setForeground(new java.awt.Color(153, 0, 0));
        lblNBV.setText("0");
        jPanel3.add(lblNBV, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 280, 250));

        lblClima.setFont(new java.awt.Font("GungsuhChe", 1, 14)); // NOI18N
        lblClima.setForeground(new java.awt.Color(0, 102, 0));
        lblClima.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClima.setText("CLIMA");
        jPanel1.add(lblClima, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 120, -1));

        lblTerreno.setFont(new java.awt.Font("GungsuhChe", 1, 14)); // NOI18N
        lblTerreno.setForeground(new java.awt.Color(0, 102, 0));
        lblTerreno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTerreno.setText("TERRENO");
        jPanel1.add(lblTerreno, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 120, -1));

        jLabel14.setFont(new java.awt.Font("GungsuhChe", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 51, 51));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Simulador de Batalha Aleatória");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        btnBatalha.setFont(new java.awt.Font("GungsuhChe", 1, 18)); // NOI18N
        btnBatalha.setForeground(new java.awt.Color(0, 102, 51));
        btnBatalha.setText("BATALHA!");
        btnBatalha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalhaActionPerformed(evt);
            }
        });
        jPanel1.add(btnBatalha, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 120, -1));

        labelClima.setFont(new java.awt.Font("GungsuhChe", 1, 18)); // NOI18N
        labelClima.setForeground(new java.awt.Color(0, 102, 51));
        labelClima.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelClima.setText("CLIMA");
        jPanel1.add(labelClima, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 120, -1));

        labelTerreno.setFont(new java.awt.Font("GungsuhChe", 1, 18)); // NOI18N
        labelTerreno.setForeground(new java.awt.Color(0, 102, 51));
        labelTerreno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTerreno.setText("TERRENO");
        jPanel1.add(labelTerreno, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 695, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarActionPerformed
        // TODO add your handling code here:
        lblSitA.setVisible(true);
        lblSitB.setVisible(true);
        labelClima.setVisible(true);
        lblClima.setVisible(true);
        labelTerreno.setVisible(true);
        lblTerreno.setVisible(true);
        
        
        btnBatalha.setVisible(true);
        
        nBB=0;
        nBBA=0;
        nBBV=0;
        
        double numTA = (100+Math.random()*(10001-100));//num de tropas de 100 a 1000
        nTA = (int)numTA;
        lblNTA.setText(Integer.toString(nTA));
                
        double numTV = (100+Math.random()*(10001-100));
        nTV = (int)numTV;
        lblNTV.setText(Integer.toString(nTV));
        
        double numMA = (1+Math.random()*(101-1));//moral de 1 a 100
        nMA = (int)numMA;
        
                
        double numMV = (1+Math.random()*(101-1));
        nMV = (int)numMV;
        
        
        double sitR = (0+Math.random()*(2-0));
        int sitRandom =(int)sitR;
        
        if(sitRandom==0){
            lblSitA.setText("ATACANDO");
            lblSitB.setText("DEFENDENDO");
            nBBA+=4;
            nBBV+=2;
            
        }else{
            lblSitB.setText("ATACANDO");
            lblSitA.setText("DEFENDENDO");
            nBBV+=4;
            nBBA+=2;
        }
        
        double sitClima = (0+Math.random()*(4-0));
        int sitClimaR =(int)sitClima;
        
        switch(sitClimaR){
            case 0:
                lblClima.setText("LIMPO");
                nMA+=10;
                nMV+=10;
                nBB+=4;
            break;
            
            case 1:
                lblClima.setText("NUBLADO");
                nMA-=10;
                nMV-=10;
                nBB+=6;
            break;
            
            case 2:
                lblClima.setText("CHUVOSO");
                nMA-=20;
                nMV-=20;
                nBB+=8;
            break;
            
            case 3:
                lblClima.setText("NEVASCA");
                nMA-=25;
                nMV-=25;
                nBB+=10;
            break;
                
        }
        
        double sitTerreno = (0+Math.random()*(4-0));
        int sitTerrenoR =(int)sitTerreno;
        
        sitA = lblSitA.getText();
        sitB = lblSitB.getText();
        switch(sitClimaR){
            case 0:
                lblTerreno.setText("PLANO");
                if(sitA=="ATACANDO"){
                    nMA+=15;
                    nMV+=10;
                    nBBA+=3;
                    nBBV-=3;
                }else{
                    nMA+=10;
                    nMV+=15;
                    nBBA-=3;
                    nBBV+=3;
                }
                
                
            break;
            
            case 1:
                lblTerreno.setText("MONTANHOSO");
                if(sitA=="ATACANDO"){
                    nMA-=20;
                    nMV+=30;
                    nBBA+=3;
                    nBBV+=1;
                }else{
                    nMA+=30;
                    nMV-=20;
                    nBBA+=1;
                    nBBV+=3;
                } 
                
                
            break;
            
            case 2:
                lblTerreno.setText("PANTANOSO");
                if(sitA=="ATACANDO"){
                    nMA-=20;
                    nMV-=10;
                    nBBA+=2;
                    nBBV+=3;
                }else{
                    nMA-=10;
                    nMV-=20;
                    nBBA+=3;
                    nBBV+=2;
                } 
            break;
            
            case 3:
                lblTerreno.setText("FLORESTA");
                if(sitA=="ATACANDO"){
                    nMA-=5;
                    nMV+=10;
                    nBBA+=2;
                    nBBV+=2;
                }else{
                    nMA+=10;
                    nMV-=5;
                    nBBA+=2;
                    nBBV+=2;
                } 
            break;
            
        }
        if(nMA<=0){
            nMA=1;
        }
        if(nMV<=0){
            nMV=1;
        }
        
        lblMA.setText(Integer.toString(nMA));
        lblMV.setText(Integer.toString(nMV));
        
        lblResultado.setVisible(false);
        lblNBA.setVisible(false);
        lblNBV.setVisible(false);
        labelBA.setVisible(false);
        labelBV.setVisible(false);
        
    }//GEN-LAST:event_btnGerarActionPerformed

    
    
    private void btnBatalhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalhaActionPerformed
        // TODO add your handling code here:
             
        
        
        nBBA+=nBB;
        nBBV+=nBB;
        
        int nBA = (nTA/nMA)*nBBA;       
        int nBV = (nTV/nMV)*nBBV; 
        
        if(nBA>nTA){
            nBA=nTA;
        }
        
        if(nBV>nTV){
            nBV=nTV;
        }
        
        lblNBA.setText(Integer.toString(nBA));
        lblNBV.setText(Integer.toString(nBV));
        
        int forcaAzul = nTA*nMA;
        int forcaVermelha = nTV*nMV;
        
        if(sitA=="ATACANDO"&&(forcaAzul>forcaVermelha)){
            lblResultado.setForeground(Color.blue);
            lblResultado.setText("EXÉRCITO AZUL ATACOU COM SUCESSO!");
            nMA+=10;
        }else if(sitA=="DEFENDENDO"&&(forcaAzul>forcaVermelha)){
            lblResultado.setForeground(Color.blue);
            lblResultado.setText("EXÉRCITO AZUL DEFENDEU COM SUCESSO!");
            nMA+=20;
        }else if(sitB=="ATACANDO"&&(forcaAzul<forcaVermelha)){
            lblResultado.setForeground(Color.red);
            lblResultado.setText("EXÉRCITO VERMELHO ATACOU COM SUCESSO!");
            nMV+=10;
        }else if(sitB=="DEFENDENDO"&&(forcaAzul<forcaVermelha)){
            lblResultado.setForeground(Color.red);
            lblResultado.setText("EXÉRCITO VERMELHO DEFENDEU COM SUCESSO!");
            nMV+=20;
        }else{
           
            lblResultado.setText("EMPATE!"); 
            nMA-=10;
            nMV-=10;
        }
        
        if(nMA<0){
            nMA=1;
        }
        if(nMV<0){
            nMV=1;
        }
        
        
        lblNBV.setVisible(true);
        lblNBA.setVisible(true);
        lblResultado.setVisible(true);
        labelBV.setVisible(true);
        labelBA.setVisible(true);
        lblMA.setText(Integer.toString(nMA));
        lblMV.setText(Integer.toString(nMV));
        btnBatalha.setVisible(false);
        
        
        
        
    }//GEN-LAST:event_btnBatalhaActionPerformed
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatalha;
    private javax.swing.JButton btnGerar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelBA;
    private javax.swing.JLabel labelBV;
    private javax.swing.JLabel labelClima;
    private javax.swing.JLabel labelTerreno;
    private javax.swing.JLabel lblClima;
    private javax.swing.JLabel lblMA;
    private javax.swing.JLabel lblMV;
    private javax.swing.JLabel lblNBA;
    private javax.swing.JLabel lblNBV;
    private javax.swing.JLabel lblNTA;
    private javax.swing.JLabel lblNTA1;
    private javax.swing.JLabel lblNTV;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblSitA;
    private javax.swing.JLabel lblSitB;
    private javax.swing.JLabel lblTerreno;
    // End of variables declaration//GEN-END:variables
}
